---

- name: Mount Root Volume
  command: /bin/bash -c "mount /dev/{{ root_device_name }} /mnt/"
  sudo: True

- name: Make Root Directories
  command: /bin/bash -c "mkdir -p /mnt/proc /mnt/etc /mnt/dev /mnt/var /mnt/sys /mnt/tmp /mnt/boot"
  sudo: True

- name: Mount Boot
  command: /bin/bash -c "mount /dev/{{ boot_device_name }}1 /mnt/boot"
  sudo: True

- name: Make Second Level Directories
  command: /bin/bash -c "mkdir -p /mnt/var/log /mnt/var/cache /mnt/var/lock/rpm"
  sudo: True

- name: Make Audit Directory
  command: /bin/bash -c "mkdir -p /mnt/var/log/audit"
  sudo: True

- name: Unmount Bind Mounts
  mount:
    name: "{{ item.name }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    state: unmounted
  with_items:
   - { name: "/mnt/dev/pts", src: "devpts", fstype: "devpts" }
   - { name: "/mnt/dev/shm", src: "tmpfs", fstype: "tmpfs" }
   - { name: "/mnt/proc", src: "proc", fstype: "proc" }
   - { name: "/mnt/sys", src: "sysfs", fstype: "sysfs" }
   - { name: "/mnt/dev", src: "devtmpfs", fstype: "devtmpfs" }

- name: Clean Chroot Environment
  file: path={{ item.path }} state=absent
  with_items:
   - { path: '/mnt/dev/console' }
   - { path: '/mnt/dev/null' }
   - { path: '/mnt/dev/zero' }
  sudo: True

- name: Setup Chroot Environment
  command: /bin/bash -c "mknod {{ item.path }} c {{ item.major_device_number }} {{ item.minor_device_number }}"
  with_items:
   - { path: '/mnt/dev/console', major_device_number: '5', minor_device_number: '1' }
   - { path: '/mnt/dev/null', major_device_number: '1', minor_device_number: '3' }
   - { path: '/mnt/dev/zero', major_device_number: '1', minor_device_number: '5' }
  sudo: True

- name: Setup Bind Mounts
  command: /bin/bash -c "mount -o bind {{ item.host_device }} {{ item.chroot_device }}"
  with_items:
   - { host_device: "/dev", chroot_device: "/mnt/dev" }
   - { host_device: "/dev/pts", chroot_device: "/mnt/dev/pts" }
   - { host_device: "/dev/shm", chroot_device: "/mnt/dev/shm" }
   - { host_device: "/proc", chroot_device: "/mnt/proc" }
   - { host_device: "/sys", chroot_device: "/mnt/sys" }
  sudo: True
